"""Pure-Python unit tests for the ASGI bridge harness.

These tests extract the Python source that is embedded (inline) inside ``worker.js``
and exercise it directly, without Pyodide or a browser. This is the fast inner TDD
loop: it verifies the exact harness + FastAPI app code that ships in the browser,
so the two cannot drift apart.
"""

import asyncio
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent.parent
BRIDGE_JS = HERE / "bridge-python.js"
WORKER_JS = HERE / "worker.js"


def extract_python(const_name: str, js_file: pathlib.Path) -> str:
    """Pull the contents of `const <const_name> = String.raw`...`;` out of a JS file."""
    src = js_file.read_text()
    match = re.search(
        r"const " + re.escape(const_name) + r" = String\.raw`(.*?)`;",
        src,
        re.S,
    )
    assert match, f"could not find embedded python block {const_name} in {js_file.name}"
    return match.group(1)


def load_namespace():
    ns: dict = {}
    exec(extract_python("ASGI_BRIDGE_PY", BRIDGE_JS), ns)
    exec(extract_python("APP_PY", WORKER_JS), ns)
    return ns


def make_bridge():
    ns = load_namespace()
    return ns["ASGIBridge"](ns["app"], root_path="/app")


def call(method, path, *, query="", headers=None, body=b""):
    """Boot a fresh bridge (running lifespan) and handle one request."""
    headers = headers or [("host", "127.0.0.1:8000")]

    async def go():
        bridge = make_bridge()
        await bridge.startup()
        return await bridge.handle(
            method, path, query, headers, body,
            scheme="http", host="127.0.0.1", port=8000,
        )

    return asyncio.run(go())


def test_lifespan_startup_populates_items():
    # The FastAPI startup event seeds ITEMS; the JSON endpoint must reflect that.
    res = call("GET", "/app/api/items")
    assert res["status"] == 200
    assert b'"items"' in res["body"]
    assert b"Widget" in res["body"] and b"Gadget" in res["body"]


def test_home_page_renders_and_links_carry_prefix():
    res = call("GET", "/app/")
    assert res["status"] == 200
    body = res["body"]
    assert b"home-marker" in body
    # url_for() must emit URLs that include the /app root_path so they stay
    # inside the service-worker-intercepted scope.
    assert b"/app/about" in body
    assert b"/app/widget" in body
    assert b"/app/submit" in body


def test_about_navigation():
    res = call("GET", "/app/about")
    assert res["status"] == 200
    assert b"about-marker" in res["body"]


def test_form_post_redirects_with_prefix():
    body = b"name=Simon"
    res = call(
        "POST", "/app/submit",
        headers=[
            ("host", "127.0.0.1:8000"),
            ("content-type", "application/x-www-form-urlencoded"),
            ("content-length", str(len(body))),
        ],
        body=body,
    )
    assert res["status"] == 303
    location = dict((k.lower(), v) for k, v in res["headers"]).get("location")
    assert location is not None
    assert "/app/thanks" in location
    assert "name=Simon" in location


def test_thanks_page_shows_name():
    res = call("GET", "/app/thanks", query="name=Simon")
    assert res["status"] == 200
    assert b"Thanks, Simon!" in res["body"]


def test_widget_page_embeds_its_own_fetch_script():
    res = call("GET", "/app/widget")
    assert res["status"] == 200
    body = res["body"]
    # The page must carry inline JS that fetches the (also-intercepted) JSON API.
    assert b"<script>" in body
    assert b"/app/api/items" in body


def test_unknown_route_is_404():
    res = call("GET", "/app/nope")
    assert res["status"] == 404


def test_synthesized_host_header_includes_nondefault_port():
    # In a service worker the browser-managed Host header is not forwarded, so the
    # bridge must synthesize one. It MUST include the non-default port, otherwise
    # url_for()/redirects emit port-less URLs that fail in the browser.
    async def go():
        bridge = make_bridge()
        await bridge.startup()
        # No host header supplied -> bridge synthesizes it from host + port.
        return await bridge.handle(
            "GET", "/app/", "", [], b"", scheme="http", host="127.0.0.1", port=59157
        )

    res = asyncio.run(go())
    assert res["status"] == 200
    # Links generated by url_for must carry the port.
    assert b"127.0.0.1:59157/app/about" in res["body"]
    assert b"127.0.0.1/app/about" not in res["body"].replace(b"127.0.0.1:59157", b"")
