// Generated by Wrangler by running `wrangler types`

interface Env {
	API_KEY: "dev-api-key-12345";
	BROWSER_SESSION: DurableObjectNamespace<import("./src/index").BrowserSession>;
	BROWSER: Fetcher;
}
